### ISSUE TITLE
артиллерия будет?

### ISSUE THREAD

**Issue by 1im** [rempopo/CO35_Operation_blue_spoon.lingor3#4]
https://github.com/rempopo/CO35_Operation_blue_spoon.lingor3/blob/8f0debb95af083bc4895ee82d5288d394f92a319/dzn_tSFramework/dzn_tSFramework_Init.sqf#L25

**Comment by Comrade333** [comment]
не завезли

**Comment by Comrade333** [comment]
ток дымы
