### ISSUE TITLE
хелп сет тайм

### ISSUE THREAD

**Issue by Comrade333** [rempopo/CO35_Operation_blue_spoon.lingor3#6]
https://github.com/rempopo/CO35_Operation_blue_spoon.lingor3/blob/6801293425003e2cec3d74ca2923103c05106f46/initServer.sqf#L5-L17
@10Dozen помохи сделать время 5:30

**Comment by 1im** [comment]
all works actually

**Comment by 10Dozen** [comment]
Поровнее фикс, правда потестить нужна на всякий случай
https://github.com/rempopo/CO35_Operation_blue_spoon.lingor3/pull/9
