### ISSUE TITLE
Замени на ФН Миними

### ISSUE THREAD

**Issue by 10Dozen** [rempopo/CO35_Operation_blue_spoon.lingor3#7]
https://github.com/rempopo/CO35_Operation_blue_spoon.lingor3/blob/618adbfc558d2cb3dd3881ea4cf09c2a269fe4ba/dzn_gear/Kits.sqf#L101

М249 с перфорированной крышкой над стволом, а судя по фоткам там были еще Миними (без крышки)

https://i.pinimg.com/736x/de/14/87/de1487ee773189cbd754d4bb9a1ae464--marines-ranger.jpg

**Comment by Comrade333** [comment]
кинь фоточку

**Comment by Comrade333** [comment]
ааа

**Comment by OneScheer** [comment]
Падажжи, FN Minimi это и есть M249. В РХС-е он как раз аутентичный.

**Comment by Comrade333** [comment]
я ставил как раз такие же как и на фото

**Comment by 10Dozen** [comment]
Ну я по класснейму тока смотрел, если без крышки то збс, можешь закрыть
