### ISSUE TITLE
Формат названия ниправильный

### ISSUE THREAD

**Issue by 10Dozen** [rempopo/CO35_Operation_blue_spoon.lingor3#8]
kit_{KEY}_{ROLE} -- нужно заменить везде на kit_panama_random

https://github.com/rempopo/CO35_Operation_blue_spoon.lingor3/blob/618adbfc558d2cb3dd3881ea4cf09c2a269fe4ba/dzn_gear/Kits.sqf#L209

**Comment by Comrade333** [comment]
готово

**Comment by 10Dozen** [comment]
Согласен
